Feature/merchant one
kingandpartners/active_merchant pull request #12
Opened 2017-03-16 16:34 UTC by sagararathi

Merchant One integration 

Note

In this PR
I have removed ssl version ``` http.ssl_version = :SSLv3``` as this is been removed in original repo here is commit https://github.com/activemerchant/active_merchant/commit/98188f1b5c74a647ace4260bf2c7866a59e2b909

secondly I have refactored ``` def commit ``` in file  ``` lib/active_merchant/billing/gateways/merchant_one.rb ```  I have removed argument from this method because it's never be used and also it  was adding dependency to other method like ```store, unstore, void ``` which done not require any money to do that api call.

thirdly there are few API calls which does not require any type to be added. so I have added check to ``` def post_data ``` to check if the type is passed ``` nil ``` or empty string to include or exclude type in API call

2017-03-21 19:15 UTC, kilgore5 requested changes

2017-03-21 19:15 UTC, kilgore5 commented on lib/active_merchant/billing/gateways/merchant_one.rb
> +        post['customer_vault'] = 'add_customer'
convert this to a function like `add_customer_vault` to follow the patterh of the other functions

2017-03-21 19:15 UTC, kilgore5 commented on lib/active_merchant/billing/gateways/merchant_one.rb
> +        post['customer_vault'] = 'add_customer'
also, make consistent with symbols instead of string if possible (across whole file)

2017-04-19 17:57 UTC, jGRUBBS requested changes
@sagararathi can you add the remote tests for the new methods you added to merchant one(void, refund, store, and unstore)? Once you do that this is good to go.

2017-04-25 20:17 UTC, sagararathi commented
@jGRUBBS I have added remote test. Please review and let me know if there is any feedback. Thanks @kilgore5 @jGRUBBS

2017-04-25 20:26 UTC, jGRUBBS commented
🎉  good work @sagararathi :shipit:

2017-04-25 20:26 UTC, merged